import { createClient as createServiceClient } from "@supabase/supabase-js";
import type { MessageType } from "@/types/database";

const supabaseAdmin = createServiceClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
);

/**
 * Creates a system message in the chat for an application.
 * System messages are auto-generated by the platform — not sent by a user.
 * They appear in the chat as status updates (e.g., "Interview requested",
 * "First name revealed", "Interview confirmed").
 *
 * @param applicationId - The application this message belongs to
 * @param text - The message text displayed in the chat
 * @param messageType - The type of system message for rendering purposes
 * @param metadata - Optional JSON metadata (e.g., interview schedule details)
 */
export async function createSystemMessage(
  applicationId: string,
  text: string,
  messageType: MessageType = "system",
  metadata?: Record<string, unknown>
): Promise<void> {
  try {
    // Use a deterministic "system" sender. We use the application_id owner as
    // a fallback since sender_id is NOT NULL and references auth.users.
    // However, for system messages we set sender_type = 'system' so the UI
    // knows not to show a user avatar.
    //
    // Get the candidate user_id from the application to use as sender_id
    // (required by FK constraint, but sender_type='system' marks it as automated)
    const { data: app } = await supabaseAdmin
      .from("applications")
      .select("user_id")
      .eq("id", applicationId)
      .single();

    if (!app) {
      console.error("[systemMessage] Application not found:", applicationId);
      return;
    }

    await supabaseAdmin.from("messages").insert({
      application_id: applicationId,
      sender_id: app.user_id,
      sender_type: "system",
      message_text: text,
      message_type: messageType,
      metadata: metadata || null,
    });
  } catch (err) {
    // System messages should never block the main operation
    console.error("[systemMessage] Failed to create:", err);
  }
}
